package csis3275.project.seasell.account.model;

public enum TransactionType {
    DEPOSIT_FULFILLED, WITHDRAWAL_REQUESTED, WITHDRAWAL_REJECTED, PURCHASE_CREDIT_HOLD, PURCHASE_CREDIT_RELEASE,
    SALES_PROCEED,
}
